import React from "react";
import { Divider } from "antd";
import "bootstrap";
import './Home.scss';
import workflow from '../../assets/workflow.png';
export class Home extends React.Component {
  render() {
    return (
      <div className="container">
        <div className="row">
          <div className="col-md-6 mt-5">
            <p className="info">
              Today, massive amounts of data are generated by Next-Generation
              Sequencing (NGS) technologies. In recent years, many algorithms,
              statistical methods, and software tools have been developed to
              perform the individual analysis steps of various NGS applications.
              However, streamlined analysis remains a significant barrier to
              effectively utilizing the technology. We have developed a Python
              package (pySeqRNA) that allows fast, efficient, manageable, and
              reproducible RNA-Seq analysis. It effectively uses current
              software and tools with newly written Python scripts without
              confining users to a collection of pre-defined methods and
              environments by combining many command-line tools and custom
              Python scripts.
            </p>
          </div>
          <div className="col-md-6">
              <img src={workflow} height={400} alt='workflow'></img>
          </div>
        </div>
        <div className="row mt-5">
            <h5>Please Cite</h5>
            <p className="info"> Duhan N and Kaundal R. pySeqRNA: an automated Python package for RNA sequencing data analysis [version 1; not peer reviewed]. F1000Research 2020, 9(ISCB Comm J):1128 (poster) (https://doi.org/10.7490/f1000research.1118314.1) </p>
        </div>
      </div>
    );
  }
}
